
/**
 * APP_CONTENT
 * The single source of truth for all text and copy in the application.
 * Edit this file to change headings, prompts, or messages throughout the site.
 */

export const APP_CONTENT = {
  auth: {
    title: "Our Private Space",
    subtitle: "Enter the date it all began",
    unlockButton: "Unlock Memories",
    openingButton: "Opening...",
    monthLabel: "Month",
    dayLabel: "Day",
    yearLabel: "Year",
    selectPrompt: "Select",
    months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    days: Array.from({ length: 31 }, (_, i) => (i + 1).toString().padStart(2, '0')),
    years: ['2022', '2023', '2024', '2025'],
  },
  navigation: {
    us: "Us",
    moments: "Moments",
    letters: "Letters",
    watch: "Watch",
    plans: "Plans",
    logout: "Log Out",
    signature: "Aldo & Fiona",
  },
  home: {
    heroTitle: "Together Since",
    heroQuote: '"Two souls, one date, a thousand memories in the making."',
    thoughtTitle: "A Thought For Today",
    thoughtContent: "Fiona, looking back at Feb 25th is the best thing I do every day.",
    thoughtFooter: "From Aldo",
    milestoneTitle: "Milestones",
    milestoneEmpty: "Savoring every second with you.",
    milestoneToday: "Today!",
    milestoneDaysLeft: "days left",
    watchTitle: "Binge Night",
    watchSubtitle: "Our story in shows.",
    watchBadge: "Items",
    watchExplore: "Explore Collection",
  },
  countdown: {
    years: "Years",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
  },
  memories: {
    title: "Our Moments",
    subtitle: "Capturing our beautiful life, frame by frame.",
    viewSlideshow: "Slideshow",
    viewGrid: "Grid",
    playMovie: "Play Movie",
    addMedia: "Add Photo / Video",
    uploading: "Uploading...",
    loading: "Loading Memories...",
    deleteConfirm: "Are you sure you want to delete this memory?",
    editMemory: "Edit Memory",
    refineMoment: "Refine the moment",
    saveChanges: "Save Changes",
    deleteMemory: "Delete Memory",
    playFromHere: "Play from here",
    signature: "Fiona + Aldo",
    captionPlaceholder: "What happened here?",
    dateLabel: "Date",
    captionLabel: "Caption",
  },
  letters: {
    title: "Letters",
    subtitle: "Shared thoughts, saved for now and forever.",
    tabNotes: "Notes",
    tabSealed: "Sealed",
    notes: {
      title: "Notes",
      subtitle: "Spoken and written thoughts, shared only here.",
      placeholder: "Write or record a note...",
      recording: "Recording...",
      ready: "Note Ready",
      authorAldo: "Aldo",
      authorFiona: "Fiona",
    },
    sealed: {
      title: "Future Letters",
      subtitle: "Voices that only time will reveal.",
      writeButton: "Write Letter",
      unlocksOn: "Unlocks on",
      readMessage: "Read Message",
      modalTitle: "A Letter for Tomorrow",
      modalSubtitle: "Pour your heart out, we'll seal it away.",
      fromLabel: "From",
      toLabel: "To",
      dateLabel: "Unlock Date",
      subjectLabel: "Subject",
      contentLabel: "Letter Content",
      subjectPlaceholder: "Title for this memory...",
      contentPlaceholder: "Pour your heart out...",
      submitButton: "Seal it Forever",
      readerGreeting: "To my dearest",
      readerClosing: "With all my love,",
      readerSealed: "Sealed",
      readerUnveiled: "Unveiled",
    }
  },
  calendar: {
    title: "Planning",
    subtitle: "Shared moments & milestones",
    anniversaryLabel: "Anniversary",
    milestoneBadge: "Milestone Anniversary",
    daysUs: "Celebrating 730 days of us",
    defaultSpecial: "A day to celebrate us",
    openSurprise: "Open Anniversary Surprise",
    updateFor: "Update for:",
    statusLabel: "Status",
    statusFree: "Free",
    statusBusy: "Busy",
    statusMaybe: "Maybe",
    statusNone: "None",
    closeDetails: "Close Details",
  },
  watchlist: {
    title: "Our Watchlist",
    subtitle: "What we are watching together.",
    placeholder: "Search movie or show...",
    save: "Save",
    progress: "Progress",
    updateFor: "Update for",
  },
  valentine: {
    proposal: "Will you be my Valentine?",
    initialMessage: "A special question for a special soul",
    yesButton: "Yes, Always ❤️",
    noButton: "No",
    bruhText: "bruhhh",
    successTitle: "Forever Yours!",
    successTitleEvasive: "You're Mine!",
    successQuote: '"In all the world, there is no heart for me like yours."',
    enterButton: "Enter Our Space",
    footer: "Aldo & Fiona • Celebrating Our Love",
    roasts: [
      "Wait, misclick? 🤨", 
      "The 'Yes' button is right there... 👉", 
      "Are you actually trying? 💀", 
      "Stop playing, Fiona! 🏃💨",
      "Calculated evasion... 🧠",
      "Still going? Relentless. 🚩"
    ]
  },
  anniversary: {
    title: "Happy Anniversary, My Love!",
    initialMessage: "Celebrating the day our world changed",
    yesButton: "Happy Anniversary! ❤️",
    noButton: "Not Yet",
    successTitle: "To Many More!",
    successQuote: '"Every year with you is my favorite year yet."',
    enterButton: "Enter Our Memories",
    footer: "Aldo & Fiona • Another Year Together"
  }
};
