
/**
 * APP_CONTENT
 * The single source of truth for all text and copy in the application.
 * Edit this file to change headings, prompts, or messages throughout the site.
 */

export const APP_CONTENT = {
  auth: {
    title: "Fioni & Aldos really cool website",
    subtitle: "How long have you been dating",
    unlockButton: "Enter date for right of passage",
    openingButton: "Opening...",
    monthLabel: "Month",
    dayLabel: "Day",
    yearLabel: "Year",
    selectPrompt: "Select",
    months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    days: Array.from({ length: 31 }, (_, i) => (i + 1).toString().padStart(2, '0')),
    years: ['2022', '2023', '2024', '2025'],
  },
  navigation: {
    us: "Home",
    moments: "Pictures",
    letters: "Letters",
    watch: "Watch",
    plans: "Plans",
    logout: "Log Out",
    signature: "Aldo & Fiona",
  },
  home: {
    heroTitle: "Its been this long ive been with my bebe dook",
    heroQuote: '"it all started with you showing me your rock <3."',

    milestoneTitle: "Important Dates",
    milestoneEmpty: "nothing yet come back soon bebe dook",
    milestoneToday: "Today!",
    milestoneDaysLeft: "days left",
    watchTitle: "rot watchlist",
    watchSubtitle: "look up show/movie and we watch together <3",
    watchBadge: "Items",
    watchExplore: "Explore Collection",
  },
  countdown: {
    years: "Years",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
  },
  memories: {
    title: "we need more pictures of us bebe",
    subtitle: "Our collection of pictures n shi",
    viewSlideshow: "Slideshow",
    viewGrid: "Grid",
    playMovie: "Play Movie",
    addMedia: "Add Photo / Video",
    uploading: "Uploading...",
    loading: "Loading Memories...",
    deleteConfirm: "Are you sure you want to delete this memory?",
    editMemory: "Edit Memory",
    refineMoment: "Refine the moment",
    saveChanges: "Save Changes",
    deleteMemory: "Delete Memory",
    playFromHere: "Play from here",
    signature: "Fiona + Aldo",
    captionPlaceholder: "What happened here?",
    dateLabel: "Date",
    captionLabel: "Caption",
  },
  letters: {
    title: "Letters",
    subtitle: "we can write little notes for eachother -_-",
    tabNotes: "Quick Notes",
    tabSealed: "Sealed",
    notes: {
      title: "Quick Notes",
      subtitle: "",
      placeholder: "Write or record a note...",
      recording: "Recording...",
      ready: "Note Ready",
      authorAldo: "Aldo",
      authorFiona: "Fiona",
    },
    sealed: {
      title: "Future Letters",
      subtitle: "Write a letter to be opened on a future date.",
      writeButton: "Write Letter",
      unlocksOn: "Unlocks on",
      readMessage: "Read Message",
      modalTitle: "A Letter for Tomorrow",
      modalSubtitle: "get all corny for me bby ;)",
      fromLabel: "From",
      toLabel: "To",
      dateLabel: "Unlock Date",
      subjectLabel: "Subject",
      contentLabel: "Letter Content",
      subjectPlaceholder: "Title for this memory...",
      contentPlaceholder: "lemme hear it...",
      submitButton: "Seal it Forever",
      readerGreeting: "To my hot lover",
      readerClosing: "<3,",
      readerSealed: "Sealed",
      readerUnveiled: "Unveiled",
    }
  },
  calendar: {
    title: "Planning",
    subtitle: "Shared moments & milestones",
    anniversaryLabel: "Anniversary",
    milestoneBadge: "Milestone Anniversary",
    daysUs: "Celebrating 730 days of us",
    defaultSpecial: "A day to celebrate us",
    openSurprise: "Open Anniversary Surprise",
    updateFor: "Update for:",
    statusLabel: "Status",
    statusFree: "Free",
    statusBusy: "Busy",
    statusMaybe: "Maybe",
    statusNone: "None",
    closeDetails: "Close Details",
  },
  watchlist: {
    title: "Our Watchlist",
    subtitle: "What we are watching together.",
    placeholder: "Search movie or show...",
    save: "Save",
    progress: "Progress",
    updateFor: "Update for",
  },
  valentine: {
    proposal: "Will you be my Valentine?",
    initialMessage: "pretty pls",
    yesButton: "Yurr ❤️",
    noButton: "No",
    bruhText: "wurdafuck? 😢",
    successTitle: "huzaaah!",
    successTitleEvasive: "I love you my love!",
    successQuote: '"I hope you like my nerdy ahh Valentines Gift"',
    enterButton: "look look look 👀",
    footer: "Aldo & Fiona Incorperrated Trademark",
    roasts: [
      "heheh you misssed the yes button", 
      "you tripping bruh? 💀", 
      "quit tweaking bruh", 
      "ill piss on your bed",
      "sumimase, wtf",
      "do it again i dare you"
    ]
  },
  anniversary: {
    title: "Happy Anniversary, My Love!",
    initialMessage: "Celebrating the day our world changed",
    yesButton: "Happy Anniversary! ❤️",
    noButton: "Not Yet",
    successTitle: "To Many More!",
    successQuote: '"Every year with you is my favorite year yet."',
    enterButton: "Enter Our Memories",
    footer: "Aldo & Fiona • Another Year Together"
  }
};
